"""
Answer composition with mandatory citations.

Answers are composed from templates rather than generated by an LLM. That is a
deliberate choice, not a shortcut:

  * The claim of this project is that the MEMORY is good, not that the language
    model is. Putting a generative model at the end would let fluent prose paper
    over a bad retrieval, which is exactly the failure mode being argued against.
  * A template answer cannot hallucinate a fact the store does not contain. Every
    number in the output traces to a row.
  * It runs on CPU with no weights, so the demo is reproducible by anyone.

An LLM can be layered on later for phrasing; it would consume this same cited
structure. The citation is the product, the sentence is packaging.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from .retriever import Retriever, Scored, expand_relations, parse_focus_time
from .types import Assertion, Closure, Seconds  # noqa: F401  (Closure used in duration caveat)


def fmt_time(t: Seconds) -> str:
    if t == float("inf"):
        return "end of video"
    m, s = divmod(max(0.0, t), 60)
    return f"{int(m):02d}:{s:05.2f}"


def fmt_span(a: Assertion) -> str:
    return f"[{fmt_time(a.interval.start)} - {fmt_time(a.interval.end)}]"


@dataclass
class Citation:
    relation: str
    object: str
    start: Seconds
    end: Seconds
    confidence: float
    closure: str
    frame_ids: tuple[int, ...] = ()

    def __str__(self) -> str:
        frames = ""
        if self.frame_ids:
            frames = (
                f", frames {self.frame_ids[0]}-{self.frame_ids[-1]}"
                if len(self.frame_ids) > 1
                else f", frame {self.frame_ids[0]}"
            )
        return (
            f"[{fmt_time(self.start)}-{fmt_time(self.end)}] "
            f"{self.relation}={self.object} (conf {self.confidence:.2f}, "
            f"{self.closure}{frames})"
        )


@dataclass
class Answer:
    text: str
    citations: list[Citation] = field(default_factory=list)
    scored: list[Scored] = field(default_factory=list)
    query_type: str = "general"

    def __str__(self) -> str:
        lines = [self.text]
        if self.citations:
            lines.append("")
            lines.append("Evidence:")
            lines.extend(f"  - {c}" for c in self.citations)
        return "\n".join(lines)

    def explain(self) -> str:
        """Full ranker transparency: why each fact surfaced."""
        lines = [f"query_type: {self.query_type}", "ranking:"]
        for s in self.scored:
            a = s.assertion
            lines.append(f"  {a.relation}={a.object:<20} {fmt_span(a)}  {s.explain()}")
        return "\n".join(lines)


def _cite(a: Assertion) -> Citation:
    return Citation(
        relation=a.relation,
        object=a.object,
        start=a.interval.start,
        end=a.interval.end,
        confidence=a.confidence,
        closure=a.interval.closure.value,
        frame_ids=a.evidence.frame_ids,
    )


# --------------------------------------------------------------------------
# Query typing
# --------------------------------------------------------------------------
_WHEN = re.compile(r"\b(when|what time|at what point)\b", re.I)
_DURATION = re.compile(r"\b(how long|duration|for how)\b", re.I)


def classify_query(query: str) -> str:
    if _DURATION.search(query):
        return "duration"
    if _WHEN.search(query):
        return "when"
    if parse_focus_time(query) is not None:
        return "at_time"
    return "general"


# --------------------------------------------------------------------------
# Composition
# --------------------------------------------------------------------------
def answer(retriever: Retriever, query: str, top_k: int = 5) -> Answer:
    qtype = classify_query(query)
    focus = parse_focus_time(query)
    scored = retriever.retrieve(query, top_k=top_k, focus_time=focus)

    if not scored:
        return Answer(
            text="I have no assertion covering that. The memory does not contain "
                 "a fact matching this query - which may mean it never happened, "
                 "or that the detector never saw it.",
            query_type=qtype,
        )

    if qtype == "at_time" and focus is not None:
        return _answer_at_time(scored, focus, qtype, expand_relations(query))
    if qtype == "when":
        return _answer_when(scored, qtype)
    if qtype == "duration":
        return _answer_duration(scored, qtype)
    return _answer_general(scored, qtype)


def _answer_at_time(
    scored: list[Scored], focus: Seconds, qtype: str, relations: set[str] | None = None
) -> Answer:
    covering = [s for s in scored if s.assertion.interval.start <= focus < s.assertion.interval.end]

    # Respect the query's relation intent. "What was I HOLDING at 0:52" must not
    # be answered with LOCATED_IN just because a location happened to cover that
    # instant. If the query named a relation and nothing of that relation covers
    # the time, the honest answer is that there is a gap.
    if relations:
        scoped = [s for s in covering if s.assertion.relation in relations]
        if scoped or any(s.assertion.relation in relations for s in scored):
            covering = scoped

    if not covering:
        pool = [s for s in scored if s.assertion.relation in relations] if relations else []
        nearest = min(
            pool or scored,
            key=lambda s: min(
                abs(s.assertion.interval.start - focus), abs(s.assertion.interval.end - focus)
            ),
        )
        a = nearest.assertion
        return Answer(
            text=(
                f"Nothing is asserted at {fmt_time(focus)}. The closest fact is "
                f"{a.relation}={a.object} over {fmt_span(a)}. Note this gap could be a "
                f"genuine absence or a missed detection - the memory cannot distinguish them."
            ),
            citations=[_cite(a)],
            scored=scored,
            query_type=qtype,
        )

    parts = [f"{s.assertion.relation}={s.assertion.object}" for s in covering]
    return Answer(
        text=f"At {fmt_time(focus)}: " + "; ".join(parts) + ".",
        citations=[_cite(s.assertion) for s in covering],
        scored=scored,
        query_type=qtype,
    )


def _answer_when(scored: list[Scored], qtype: str) -> Answer:
    best_rel = scored[0].assertion.relation
    best_obj = scored[0].assertion.object
    matching = [
        s for s in scored
        if s.assertion.relation == best_rel and s.assertion.object == best_obj
    ]
    spans = ", ".join(fmt_span(s.assertion) for s in matching)
    plural = "interval" if len(matching) == 1 else "intervals"
    return Answer(
        text=f"{best_rel}={best_obj} holds over {len(matching)} {plural}: {spans}.",
        citations=[_cite(s.assertion) for s in matching],
        scored=scored,
        query_type=qtype,
    )


def _answer_duration(scored: list[Scored], qtype: str) -> Answer:
    best_rel = scored[0].assertion.relation
    best_obj = scored[0].assertion.object
    matching = [
        s for s in scored
        if s.assertion.relation == best_rel and s.assertion.object == best_obj
    ]
    total = sum(
        s.assertion.interval.duration for s in matching if not s.assertion.interval.is_open
    )
    # "Lower bound" keys off CLOSURE, not off end==inf. An interval that runs to
    # the last frame has a finite end but was never observed to stop, so its
    # true duration is unknown - exactly the case the caveat exists for.
    open_note = ""
    if any(s.assertion.interval.closure == Closure.OPEN for s in matching):
        open_note = " (still open at the end of the video, so this is a lower bound)"
    return Answer(
        text=(
            f"{best_rel}={best_obj} for about {total:.1f}s total across "
            f"{len(matching)} interval(s){open_note}."
        ),
        citations=[_cite(s.assertion) for s in matching],
        scored=scored,
        query_type=qtype,
    )


def _answer_general(scored: list[Scored], qtype: str) -> Answer:
    top = scored[: min(3, len(scored))]
    parts = [
        f"{s.assertion.relation}={s.assertion.object} {fmt_span(s.assertion)}" for s in top
    ]
    return Answer(
        text="Most relevant facts: " + "; ".join(parts) + ".",
        citations=[_cite(s.assertion) for s in top],
        scored=scored,
        query_type=qtype,
    )
